name: Pull Request Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install LLVM and Clang
      # You may pin to the exact commit or the version.
      # uses: KyleMayes/install-llvm-action@4f17b6579351fb03506d988e59077826c366412c
      uses: KyleMayes/install-llvm-action@v1.5.5
      with:
        # The version of LLVM and Clang binaries to install.
        version: 12.0.1

    - name: Build Debug
      run: |
        cd ${{github.workspace}}/Scripts
        ./build.sh -rebuild

    - name: Build Release
      run: |
        cd ${{github.workspace}}/Scripts
        ./build.sh -rebuild -release
    
    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Lib Debug
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/libGetterBeam.so
        # The desired behavior if no files are found using the provided path.
        
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Lib Release
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-release/libGetterBeam.so
      
  Unit_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install LLVM and Clang
      # You may pin to the exact commit or the version.
      # uses: KyleMayes/install-llvm-action@4f17b6579351fb03506d988e59077826c366412c
      uses: KyleMayes/install-llvm-action@v1.5.5
      with:
        # The version of LLVM and Clang binaries to install.
        version: 12.0.1

    - name: Setup LCOV
      # You may pin to the exact commit or the version.
      # uses: hrishikesh-kadam/setup-lcov@f5da1b26b0dcf5d893077a3c4f29cf78079c841d
      uses: hrishikesh-kadam/setup-lcov@v1.0.0
    
    - name: Build && Run Test
      run: |
        git show HEAD~2 | head
        git show HEAD~1 | head
        git log | head
        cd ${{github.workspace}}/Scripts
        ./build_test.sh -rebuild -run -html
        
    - name: Universe Coverage Report
      # You may pin to the exact commit or the version.
      # uses: zgosalvez/github-actions-report-lcov@8b72ce00008730f66e6d211e54359243012b9606
      uses: zgosalvez/github-actions-report-lcov@v1.5.0
      with:
        # The coverage files to scan. For example, `coverage/lcov.*.info`
        coverage-files: ${{github.workspace}}/cmake-build-debug/Tests/GetterBeamTestCoverage
        # The minimum coverage to pass the check. Optional. Default: `0` (always passes)
        minimum-coverage: 70# optional, default is 0
        # Set the GitHub token to have the action comment the coverage summary in the pull request. This token is provided by Actions, you do not need to create your own token. Optional. Default: ``
        github-token: ${{ secrets.GITHUB_TOKEN }} # optional
        
    - name: Comment Incremental Coverage
      # You may pin to the exact commit or the version.
      # uses: thollander/actions-comment-pull-request@686ab1cab89e0f715a44a0d04b9fdfdd4f33d751
      uses: thollander/actions-comment-pull-request@v1.4.1
      with:
        # Message that should be printed in the pull request
        message: sed -n '30p' < ${{github.workspace}}/cmake-build-debug/Report/ut_incremental_coverage_report.html | cut -c 45- | rev | cut -c 8- | rev
        # Github token of the repository (automatically created by Github)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Test Executable
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Test Executable
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/GetterBeam_Test
        # The desired behavior if no files are found using the provided path.
        
    - name: Upload Coverage Report Html
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Coverage Report
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/Report
        # The desired behavior if no files are found using the provided path.
      
  Style_Check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        # Version of clang-format
        clangFormatVersion: 13
        # Formatting style to use
        style: file

    
    
      
