name: Pull Request Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Debug
      run: |
        cd ${{github.workspace}}/Scripts
        ./build.sh -rebuild
        
    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Lib Debug
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/libGetterBeam.so
        # The desired behavior if no files are found using the provided path.

    - name: Build Release
      run: |
        cd ${{github.workspace}}/Scripts
        ./build.sh -rebuild -release
        
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Lib Release
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-release/libGetterBeam.so
        # The desired behavior if no files are found using the provided path.
      
  Unit_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup LCOV
      # You may pin to the exact commit or the version.
      # uses: hrishikesh-kadam/setup-lcov@f5da1b26b0dcf5d893077a3c4f29cf78079c841d
      uses: hrishikesh-kadam/setup-lcov@v1.0.0
    
    - name: Build && Run Test
      run: |
        cd ${{github.workspace}}/Scripts
        ./build_test.sh -rebuild -run -html
        
    - name: Upload Test Executable
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Test Executable
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/GetterBeam_Test
        # The desired behavior if no files are found using the provided path.
        
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Coverage Report
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/cmake-build-debug/Report
        # The desired behavior if no files are found using the provided path.
      
  Style_Check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        # Version of clang-format
        clangFormatVersion: 13
        # Formatting style to use
        style: file

    
    
      
